### ISSUE TITLE
Semantics of "provide" macros deviates from LaTeX standard

### ISSUE THREAD

**Issue by sebastiankuhnert** [chadparry/bibleref#3]
The \provide... commands do not have the semantics of e.g. standard LaTeX \providecommand.

Proposed solution: Use \define... instead.

**Comment by chadparry** [comment]
I didn't understand this issue. The standard "\providecommand" macro works exactly like "\newcommand" except that it doesn't give you an error for commands that already exist. I thought that the bibleref provide\* commands were similar: they define something, and they don't give you an error if you are redefining something. What is the difference in semantics?

**Comment by sebastiankuhnert** [comment]
Then let me explain: By standard LaTeX semantics, I mean the following:
- "New", e.g. `\newcommand`: Give definition, error if already defined.
- "Renew", e.g. `\renewcommand`: Override definition, error if not yet defined.
- "Provide", e.g. `\providecommand`: If not yet defined, use the given definition, otherwise leave the previous definition unchanged.
- "Define", e.g. `\def`: Use the new definition unconditionally.

What I am saying in this issue is that the `\provide...` macros of bibleref-mouth's currently behave like `\define...` macros.

Of course, there are two obvious ways to fix this: We could, as I originally suggested, rename the macros to `\define...`. Or we could change their semantics to match the usual LaTeX meaning of `\provide...`. What do you think?

**Comment by chadparry** [comment]
I thought I knew what \providecommand did, but it looks like I was wrong. Let's definitely change the name of the BR commands from \provide\* to \def*.
